version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: xrd-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    restart: unless-stopped
    command: npm run dev

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: xrd-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - PYTHONPATH=/app
    restart: unless-stopped
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
  db:
    image: postgres:15.0
    container_name: xrd_postgres
    environment:
      POSTGRES_USER: "imaiharuki"
      POSTGRES_PASSWORD: "kklab"
      POSTGRES_DB: "xrd"
      TZ: "Asia/Tokyo"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  postgres_data:
