version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: xrd-frontend
    # プロキシのnginxからのアクセスなので公開不要
    # ports:
    #   - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    environment:
      # 本番環境ではproductionに変更
      - NODE_ENV=development
      # 開発時のホットリロード設定(本番では不要)
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    restart: unless-stopped
    # 本番ではnpm run build && npm startに変更
    command: npm run dev

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: xrd-backend
    # プロキシのnginxからのみアクセスするのでapiの設定を直して未公開にしたい
    # ports:
    #   - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - PYTHONPATH=/app
    restart: unless-stopped
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
  db:
    image: postgres:15.0
    container_name: xrd_postgres
    environment:
      POSTGRES_USER: "imaiharuki"
      POSTGRES_PASSWORD: "kklab"
      POSTGRES_DB: "xrd"
      TZ: "Asia/Tokyo"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # backendからのみアクセスするので公開不要
    # ports:
    #   - 5432:5432

  nginx:
    image: nginx:stable-alpine
    container_name: xrd-nginx
    ports:
      - "80:80"

    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro # readonly
    depends_on:
      - frontend
      - backend
    restart: unless-stopped

volumes:
  postgres_data:
